# Jekyll configuration

whitelist:
  - jekyll-redirect-from
  - jekyll-github-metadata

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata

exclude:
  - Makefile
  - README.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - package.json
  - .babelrc
  - yarn.lock
  - package-lock.json
  - webpack.config.js
  - node_modules
  - Dockerfile
  - docker_compose.yml
  - un-sure

# Markdown

highlighter: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true

# Defaults

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
      og_type: article
      type: article
      category: "Others"
      excerpt_separator: "<!--more-->"
      prism_languages: []

# Site info

url: https://your.site
title: Devhints / Cheatsheets

# the top nav edit button link
repository_url: https://github.com/tobyqin/cheatsheets/blob/master

# the request button name & link in home page
request_url: https://github.com/tobyqin/cheatsheets/issues/new
request_name: Ask help

host: 0.0.0.0
destination: _output #optional